// Generated by CoffeeScript 1.3.3
(function() {
  var Mail, WebMailApp, app;

  Mail = this.Mail;

  WebMailApp = (function() {

    function WebMailApp() {}

    WebMailApp.prototype.folders = ['Inbox', 'Archive', 'Sent', 'Spam', 'L/F'];

    WebMailApp.prototype.chosenFolderId = ko.observable();

    WebMailApp.prototype.chosenFolderData = ko.observable();

    WebMailApp.prototype.chosenMailData = ko.observable();

    WebMailApp.prototype.goToFolder = function(folder) {
      return location.hash = folder;
    };

    WebMailApp.prototype.showFolder = function(folder) {
      console.log("showFolder", folder, "Hello Simon");
      this.chosenFolderId(folder);
      this.chosenFolderData({
        mails: Mail.mailsForFolder(folder)
      });
      return this.chosenMailData(null);
    };

    WebMailApp.prototype.goToMail = function(mail) {
      return location.hash = mail.folder + '/' + mail.id;
    };

    WebMailApp.prototype.showMail = function(folder, mailId) {
      this.chosenFolderId(folder);
      this.chosenFolderData(null);
      return this.chosenMailData(Mail.oneForFolderAndId(folder, mailId));
    };

    return WebMailApp;

  })();

  app = new WebMailApp();

  ko.applyBindings(app);

  Sammy(function() {
    this.get('#:folder', function() {
      return app.showFolder(this.params.folder);
    });
    this.get('#:folder/:mailId', function() {
      return app.showMail(this.params.folder, this.params.mailId);
    });
    return this.get('', function() {
      return app.goToFolder(app.folders[0]);
    });
  }).run();

}).call(this);
