// Generated by CoffeeScript 1.3.3
(function() {
  var Mail, exports;

  Mail = (function() {

    function Mail(folder, mail) {
      var k, v;
      this.folder = folder;
      for (k in mail) {
        v = mail[k];
        this[k] = v;
      }
      if (this.date) {
        this.date = new Date(this.date);
      }
      console.log(this.date);
      this;

    }

    Mail.mailData = [];

    Mail.setMailData = function(mailData) {
      this.mailData = mailData;
    };

    Mail.mailsForFolder = function(folder) {
      var mail, _i, _len, _ref, _results;
      _ref = this.mailData;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mail = _ref[_i];
        _results.push(new Mail(folder, mail));
      }
      return _results;
    };

    Mail.oneForFolderAndId = function(folder, mailId) {
      return this.mailsForFolder(folder)[mailId];
    };

    return Mail;

  })();

  exports = this;

  exports.Mail = Mail;

}).call(this);
