// Generated by CoffeeScript 1.3.3
(function() {
  var Project, exports;

  Project = (function() {

    function Project(headers, data) {
      var k, v;
      this.headers = headers;
      for (k in data) {
        v = data[k];
        this[k] = v;
      }
      this;

    }

    Project.items = [];

    Project.headers = [];

    Project.setProjectData = function(dataset) {
      var item, _i, _len, _ref, _results;
      this.headers = dataset.headers;
      _ref = dataset.data;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push(this.items = Project(this.headers, item));
      }
      return _results;
    };

    Project.all = function() {
      return this.items;
    };

    return Project;

  })();

  exports = this;

  exports.Project = Project;

}).call(this);
